### ISSUE TITLE
Enhancement: add image full screen view 

### ISSUE THREAD

**Issue by fedikhatib** [freshfieldreds/muffed#12]
Maybe add a full screen and details view for the image when tapping on it with zooming.
There are many third party package for this like photoview or image_extended.
Happy coding.

**Comment by freshfieldreds** [comment]
I did have that in last releases but removed it because the the widget i was using was pretty bad so I prioritised being able to easily access comments by pressing on the image instead of the image going full screen.

I will add the feature back but using a better widget in a future release.
