### ISSUE TITLE
Add text size adjustments to different parts of the UI

### ISSUE THREAD

**Issue by KarkanAlzwayed** [freshfieldreds/muffed#7]
Feature request, not a bug. 
Not sure if there is a plan for it, but the text resizing now applies globally to the whole UI. Having text size adjustments separate for different UI elements would be ideal. The title of the post, the conent of the post, the comments etc should all have their own text resizing. That way, I won't have a big UI text whereas I only want to make the comments's text bigger. Let me know if you need to testing. 
Thanks.

**Comment by freshfieldreds** [comment]
Sounds like a good idea.  I'll add that into a near future update.

**Comment by freshfieldreds** [comment]
This feature has now been added in the latest update
